# Generated by Django 3.0.5 on 2020-09-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionnel', '0003_auto_20200913_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numero de telephone: 0998540...', max_length=150),
        ),
    ]
